#!/bin/bash
trap state ERR EXIT

function state() {
  exit $?
}

function log() {
  echo "$(date): $1"
}

function compose() {
  docker compose "$@"
}

log "Building containers"
compose build mars-rover

log "Check for unused/dead code"
compose run mars-rover vulture app/ test/ whitelist.py

log "Running tests"
compose run mars-rover pytest -s -vv --durations=50

log "Shutdown containers"
docker network prune --force && compose down --remove-orphans --volumes
