#!/bin/bash
trap state ERR EXIT

function state() {
  exit $?
}

echo "Building containers"
docker-compose build mars-rover

echo "Check for unused/dead code"
docker-compose run mars-rover vulture app/ test/ whitelist.py

echo "Running tests"
docker-compose run mars-rover pytest

echo "Running main.py"
docker-compose run mars-rover python /code/app/main.py
